#!/usr/bin/env ruby

require 'date'

POSTS_DIR = '_posts/'

post = ARGV[0]

File.open(POSTS_DIR + Date.today.strftime("%Y-%m-%d-") + post + '.md', 'w') {|f| f.write(
  "---\nlayout: post\nsection-type: post\ntitle: Title\ncategory: Programming\ntags: [ 'euler', 'c', 'python' ]\nexcerpt: EXCERPT OF THE POST\n---\n\n### Problem: \n\n### Solution: \n\n#### C: \n\n{% highlight c %}\n{% raw %}\n\n\n{% endraw %}\n{% endhighlight %} \n\n#### Python:\n\n{% highlight python %}\n{% raw %}\n\n\n{% endraw %}\n{% endhighlight %}\n\n\n#### Try it out in Python 3:\n<iframe style='width: 100%; height: 480px; border: none;' name='embedded_python_anywhere' src='https://www.pythonanywhere.com/embedded3/'></iframe>")
}

puts('[+] Created ' + post + ' post')